language: python
python:
- 3.9
cache:
  pip: true
install:
- pip install git+https://github.com/cheind/gcsl.git#egg=gcsl[dev]
script:
- python -m gcsl.examples.cartpole train -num-gcsl-steps 100 -eval-freq 100 -num-eps-eval 1 -render-freq 100
- python -m gcsl.examples.cartpole eval -num-episodes 1 -render-freq 100 ./tmp/cartpolenet_00100.pth
notifications:
  email:
    on_success: never
    on_failure: never